[build]
  publish = "public"
  command = "echo No build command"
  node_bundler = "esbuild"

[dev]
  publish = "public"
  node_bundler = "esbuild"

[[redirects]]
  from = "/venue/:id"
  to = "/venue.html"
  status = 200

[functions]
  directory = "netlify/functions"
