[build]
  publish = "public"
  command = "echo No build command"
  node_bundler = "esbuild"

[dev]
  publish = "public"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/venue/:id"
  to = "/.netlify/functions/venue"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
